### ISSUE TITLE
Some "sum of force" values not centered in arrow

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#138]
Screenshots:
![capture](https://cloud.githubusercontent.com/assets/4051174/8867942/ffcdb89c-318d-11e5-8aba-7dba390d4fda.PNG)

Troubleshooting information (do not edit):
Name: Forces and Motion: Basics
URL: http://phet-dev.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html
Version: 1.1.0
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36
Language: en-US
Window: 1920x995
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by samreid** [comment]
I'm going to unassign the issue for now--it will be addressed when I work on all Forces and Motion: Basics issues for the upcoming S2015R redeploy.

**Comment by jessegreenberg** [comment]
While the arrows are too small to hold the value, the value is centered under the force label with a small vertical offset (like the Friction Force label in the image above.)

So we should decide how this behaves.  A few possibilities:

a) Move the 'Sum of Forces' label to the side of the arrow like the other arrow labels.
b) 'Sum of Forces' value could always be centered on the arrow, even when the arrow is too small to hold the value.
c) Leave as is since the spacing matches the other labels.
d) Others?

I am prefer option a, this is what that looks like with the different arrow sizes:

![optionb](https://cloud.githubusercontent.com/assets/6396244/12898751/7a506f18-ce6b-11e5-83a0-2eaca2c15040.PNG)
![optionb2](https://cloud.githubusercontent.com/assets/6396244/12898754/7c014602-ce6b-11e5-8ad9-92533b2bc232.PNG)

Any preferences @ariel-phet or @arouinfar or @samreid?

**Comment by arouinfar** [comment]
Great suggestion @jessegreenberg! I think option "a" looks good, and it seems to be the most consistent with the current behavior of the Friction and Applied Force vectors.

**Comment by ariel-phet** [comment]
:+1: on option "a"

**Comment by samreid** [comment]
(a) seems nice, thanks!

**Comment by jessegreenberg** [comment]
A small issue with this approach is that when the applied force is maxed out with no friction, the 'Sum of Forces' label slightly overlaps the control panel.  Perhaps this is why the label was initially above the arrow.

![overlap](https://cloud.githubusercontent.com/assets/6396244/12903829/00387078-ce88-11e5-9e8a-71cddf676530.PNG)

The 'Applied Force' arrow is very tight against the panel as well, doesn't leave much room for i18n.  How should we approach this? Reduce the label text size?  Reduce the panel size?  Move the label above the arrow again?

**Comment by ariel-phet** [comment]
@jessegreenberg I would suggest the following
 
-yes move the label above the arrow again
- if the arrow is small put the force value to the right (or left if force is negative) of the arrow
- the sum of forces aroww need to move up a little bit so as not to be touching the applied force arrow (10 pixels should give it some breathing room)

**Comment by ariel-phet** [comment]
Also for consistency, probably make the friction force arrow follow the same scheme for labeling

**Comment by jessegreenberg** [comment]
Done in commit above.  Added the 'ready for review' label, as this issue involves some layout polishing that will occur in the near future.

**Comment by jessegreenberg** [comment]
It was suggested in a 2/15/16 meeting that the 'Sum of forces' label be centered relative to the items at all times, not re-centering as the arrows change geometry.

**Comment by jessegreenberg** [comment]
At https://github.com/phetsims/forces-and-motion-basics/commit/045dea24bb99f7e479f44dd1edb27f3370d3a75d, 'Sum of Forces' arrow is centered on item stack.

**Comment by jessegreenberg** [comment]
Pixel polishing for this issue is being tracked in https://github.com/phetsims/forces-and-motion-basics/issues/166.  Otherwise, label layout is finished.  Closing.
