### ISSUE TITLE
Jittery animation and performance investigation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#172]
In 3/17/16 status meeting, @ariel-phet reported that there is some jittery behavior on his machine (Windows 10 Firefox) during sim animation.  This should be investigated and addressed before the redeploy.

@pixelzoom suggested that this may due to burdens on the garbage collector.

**Comment by jonathanolson** [comment]
Common code commits and commits to the performance-gc branch on the sim have taken it to a point where our tools don't show any objects being created (phetAllocation and https://github.com/phetsims/joist/issues/330), however usually (but not always!) there is an incremental GC step on EVERY animation frame that takes up almost exactly 10ms every time.

This seems somewhat similar to https://bugzilla.mozilla.org/show_bug.cgi?id=768282, and I'm not sure what else can be done to help with GC besides a full review of the code looking for allocations.

Running Chrome with v8 traces showed that trigger(), translate() and StringUtils.format had optimization disabled (branch has trigger => trigger0 in all cases). There could potentially be a Firefox-specific issue that is causing garbage to be created when it isn't in other browsers, and it's possible that translate() is a potential bottleneck if deoptimized.

I'd recommend addressing how important this is before tackling it further, particularly since it's a problem in the published version of the sim.

**Comment by jessegreenberg** [comment]
It seems we have three possibilities at this point for investigating this further:

- Review code, looking for any objects that are being created and destroyed every frame
- Investigate a method of listening for *all* objects that are created to understand why GC is under occasional excessive use
- Submit a bug report to Firefox as a last resort, or hope that Firefox GC improves in newer versions

Regarding the recommendation from @jonathanolson, @ariel-phet would you like to investigate this further, especially since this is an issue for published version as well?

**Comment by ariel-phet** [comment]
@jessegreenberg can you publish a latest dev version with performance improvements so I can test on a few devices? 

Generally, I would say a full review is not currently warranted, and the recent improvements may well be enough.

**Comment by jessegreenberg** [comment]
Sure, here is a dev version with a few performance improvements to reduce garbage collection.

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.5-performance-gc/forces-and-motion-basics_en.html

**Comment by ariel-phet** [comment]
@jessegreenberg definitely an improvement, lets move forward with dev testing and bump to 2.0

**Comment by jessegreenberg** [comment]
Merged gc performance enhancements into master.

**Comment by jessegreenberg** [comment]
#166 was closed, and it was determined that reducing the number of closure functions was sufficient for reducing jittery behavior and burden on the GC.  Closing.
