### ISSUE TITLE
2.0.0-rc.1 Memory Leak

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#191]
Probably a pretty big memory leak, with `?fuzzMouse=100`

Win 10 Chrome:

| Time (min) | Size (MB) | 
| ------------- |:-------------:|
| 0:00 | 35.7 |
| 0:30 | 38.4 |
| 1:00 | 39.1 |
| 1:30 | 42,9 |
| 2:00 | 42.8 |
| 2:30 | 44.3 |
| 3:00 | 42.9 |
| 3:30 | 47.3 |
| 4:00 | 48.1 |
| 4:30 | 50.5 |
| 5:00 | 52.5 |
| 6:00 | 55.1 |
| 7:00 | 58.5 |
| 10:00 | 61.8 |
| 15:00 | 67.8 |
| 16:30 | 70.0 |
| 18:15 | 75.5 |
| 20:00 | 79.2 |
| 30:00 | 96.0 |

![fambmemleak](https://cloud.githubusercontent.com/assets/5863899/14893983/b180e736-0d2e-11e6-9ff6-b89bef96eddb.PNG)

For https://github.com/phetsims/tasks/issues/583. @ariel-phet, what's the priority for addressing this?

**Comment by jessegreenberg** [comment]
This is probably worth fixing, but we should how this leak compares to the published version of the sim.  That will probably help determine priority or whether this leak needs to be patched for the release.

**Comment by jessegreenberg** [comment]
Also, perhaps this leak isn't quite as bad as the plot makes it seem since the time delta jumps from ~30 seconds around x = 2min to 10 minutes around x = 30 minutes.

However, by ~90 MB this would begin to crash on tablets after 30 minutes.

**Comment by ariel-phet** [comment]
@phet-steele please do a test on the published version

**Comment by ariel-phet** [comment]
and @phet-steele please reassign to me after test

**Comment by phet-steele** [comment]
Published version has a slower memory leak, this rc is worse.

| Time (min) | Size (MB) | 
| ------------- |:-------------:|
| 0:00 | 23.5 |
| 1:00 | 26.8 |
| 2:00 | 28.9 |
| 3:00 | 30.7 |
| 4:00 | 31.9 |
| 5:00 | 34.7 |
| 6:00 | 35.1 |
| 7:00 | 37.9 |
| 8:00 | 39.5 |
| 9:00 | 40.7 |
| 10:00 | 41.4 |
| 15:00 | 47.8 |
| 20:00 | 52.4 |
| 30:00 | 62.1 |

**Comment by ariel-phet** [comment]
@jessegreenberg leak would be good to investigate

**Comment by jessegreenberg** [comment]
Sounds good, I will look into this today.

**Comment by jessegreenberg** [comment]
The memory leaks in 2.0.0-rc.1 are caused by the common code leaks described in https://github.com/phetsims/tasks/issues/546.  This RC is using the 'stable' set of SHAs from https://github.com/phetsims/tasks/issues/476 which do not include the memory leak patches.  All of our redeployed sims have a heap profile that looks like [the plot above](https://github.com/phetsims/forces-and-motion-basics/issues/191#issue-151691111).

When the sim is profiled with common code from master, there is no indication of a memory leak.  Here is a plot of the heap size over an hour of fuzz testing with a built version of the sim and updated common code:

![untitled-1](https://cloud.githubusercontent.com/assets/6396244/14929303/12e7e29a-0e1a-11e6-9745-30aa7ecdfe3a.png)

To deploy a version that does not leak memory, we need to update the common code SHAs to master.  They could become the new stable set for https://github.com/phetsims/tasks/issues/476.

Assigning to @ariel-phet to determine if we should do that for this sim, or continue deploying this version since all other redeployed sims have this issue.  It would take about 5 minutes to deploy a new RC, but we would need to start a fresh RC test.

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet RC testing just completed with passing grades and no new issues other than this one (which really isn't even sim specific apparently).

**Comment by ariel-phet** [comment]
@jessegreenberg yes, lets do another RC with SHAs from master. This would be good to test on a production sim, so any further redeploys include this fix.

**Comment by ariel-phet** [comment]
Besides...nobody loves to make sure Master is stable more than @phet-steele :construction_worker:

**Comment by jessegreenberg** [comment]
Sounds good!  I will deploy a new RC first thing Monday after checking with other devs about the state of master.

**Comment by phet-steele** [comment]
@jessegreenberg I don't see a memory leak in 2.0.0-rc.2 (woohoo!).
