### ISSUE TITLE
Screen 1: Eliminate overlap of flag and sum of forces arrow/text

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/forces-and-motion-basics#213]
In playing with this simulation, I noticed that when the trial is complete the flag overlaps the Sum of Forces arrow, value, and text - such that it is difficult to see. It is still useful information though. 

Can the final flag move up some, and the Sum of Forces arrow move down some, such that this overlap is eliminated?

**Comment by kathy-phet** [comment]
@arouinfar - Can you take a look at this?

**Comment by arouinfar** [comment]
Here's what it looks like in 2.1.0
<img width="1009" alt="screen shot 2016-11-14 at 1 12 37 pm" src="https://cloud.githubusercontent.com/assets/8419308/20281379/89009130-aa6d-11e6-83f8-22bf737377f7.png">

The flag can be moved up by 3px, but not much more. As for moving the sum of the forces down, I see two options. We can move it down by 20 px (top) so that the vector is not occluded (but the "Sum of Forces" text is not visible), or we can move it down by 35 px (bottom) so that both the vector and label are visible. The latter option crowds the total and component forces, so I personally prefer the first option. Any thoughts @kathy-phet?
![screen shot 2016-11-14 at 1 22 14 pm](https://cloud.githubusercontent.com/assets/8419308/20281345/6200610a-aa6d-11e6-9ca5-13a3444d226f.png)
![screen shot 2016-11-14 at 1 21 53 pm](https://cloud.githubusercontent.com/assets/8419308/20281346/6202ec90-aa6d-11e6-94e8-8bc03d4da989.png)

Here's what the latter option looks like without the flag:
![screen shot 2016-11-14 at 1 29 39 pm](https://cloud.githubusercontent.com/assets/8419308/20281650/71041e02-aa6e-11e6-913f-55a5c47e9fa8.png)

**Comment by kathy-phet** [comment]
@arouinfar - 
I agree we don't want to crowd too much. What if we ... 
- cut the number of pixels of white space between the orange and green arrows in half (where white space is from the bottom most pixel of the arrow to the top most pixel of the orange arrow). 
- make the blue wins sign a bit shorter
K

**Comment by arouinfar** [comment]
@kathy-phet here's an updated mockup. There's 50px between the total force vector and the component vector, and I've reduced the height of the blue banner by 20%.

![screen shot 2016-11-15 at 4 10 05 pm](https://cloud.githubusercontent.com/assets/8419308/20328145/01050522-ab4e-11e6-8cee-2e0beff3fbae.png)

**Comment by kathy-phet** [comment]
This seems like an improvement to me. What do you think?

**Comment by arouinfar** [comment]
I agree @kathy-phet. The latest version looks pretty good to me.

**Comment by arouinfar** [comment]
@ariel-phet can you take a look at the mockup in https://github.com/phetsims/forces-and-motion-basics/issues/213#issuecomment-260800490? I think it's an improvement over the latest version. If you think we should make this change, can you reassign and prioritize?

**Comment by ariel-phet** [comment]
@arouinfar seems good to me. The banner definitely is less important than the force vectors and such, and at a smaller size it still fulfills its role.

@jessegreenberg this seems like a reasonably straightforward change, marking at medium priority, perhaps we could do a maintenance release on the latest release using the same SHA's? If it seems more involved than I am assuming, let me know.

**Comment by arouinfar** [comment]
Thanks @ariel-phet.

@jessegreenberg here's a mockup showing the changes. 
![screen shot 2016-11-16 at 11 30 29 am](https://cloud.githubusercontent.com/assets/8419308/20360221/1b8d6e46-abf0-11e6-87c2-9e884e581d52.png)

**Comment by jessegreenberg** [comment]
Should be done in https://github.com/phetsims/forces-and-motion-basics/commit/316e4cc220d1feaa52aed6bed75d9466fb7c9807.

> perhaps we could do a maintenance release on the latest release using the same SHA's

Yep, that would be best.  However, I am hitting a snag in some PhET-iO code when I checkout shas and run/build off of 2.1.  Ill check in with a Phet-iO developer about this and then we can redeploy.

**Comment by jessegreenberg** [comment]
I am hitting

> Uncaught TypeError: Cannot read property 'phetioLog' of undefined(…)

**Comment by jessegreenberg** [comment]
@samreid and @zepumph helped isolate the isssue to a missing ifphetio statement in tandem.  Sim is running off old shas again.

@arouinfar can you verify changes in this version?

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.1-rc.1/forces-and-motion-basics_en.html

If it looks good we can deploy a maintenance release off of the old shas without an RC since the minor changes were only to layout.

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!

**Comment by jessegreenberg** [comment]
Great, thanks.  Instead of deploying this right away lets also include the change to #217 since it should be quick and fit in a minor release.  Closing this issue.
