### ISSUE TITLE
Dev boundary inconsistently sized

### ISSUE THREAD

**Issue by arouinfar** [phetsims/forces-and-motion-basics#216]
While working on #213, I noticed that the dev boundary is wider on the home screen than it is on any of the individual sim screens.

<img width="1050" alt="screen shot 2016-11-16 at 11 16 37 am" src="https://cloud.githubusercontent.com/assets/8419308/20359719/47144622-abee-11e6-9799-262190a27706.png">
<img width="1049" alt="screen shot 2016-11-16 at 11 16 53 am" src="https://cloud.githubusercontent.com/assets/8419308/20359720/4714db00-abee-11e6-92d0-790234d0bc6f.png">

**Comment by marlitas** [comment]
@AgustinVallejo can you do some research here to see maybe what's going on and if it's worth trying to fix it?

**Comment by AgustinVallejo** [comment]
Found the file [`ForcesAndMotionBasicsLayoutBounds.js`](https://github.com/phetsims/forces-and-motion-basics/blob/d17992753138a1f389b45b6ab1cb3d303084bf39/js/common/view/ForcesAndMotionBasicsLayoutBounds.js) which pretty much states this is intentional and **shouldn't** be changed or it could break elements of the sim.
Closing.
