### ISSUE TITLE
User suggestion: "newtons"

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#291]
> I noticed that "Forces and Motion: Basics" spells the unit of force as "Newtons". The correct spelling is the lowercase "newtons". This is explained in section 5.3 of the SI brochure published by BIPM and available here: https://www.bipm.org/en/publications/si-brochure 
> 
> If you could update this sim (and any other affected sims) to use the correct capitalization I would appreciate it.

**Comment by arouinfar** [comment]
The user is correct, the SI unit for force is lowercase "newton".  The only place "Newton" appears in the sim is in the Applied Force NumberControl. Elsewhere, it is just the abbreviated "N". 
![Screen Shot 2022-05-16 at 4 02 13 PM (2)](https://user-images.githubusercontent.com/8419308/168690113-baefb010-c9df-4dfb-b707-0310258b7fd8.png)

I do not think this is something that needs to be fixed in a maintenance release, but we can address it the next time this sim gets republished.

**Comment by jessegreenberg** [comment]
As maintenance releases go, this one is potentially very fast since it is just a string update. I don't see "Newtons" in any other strings file in the project (though there is one case in phet-io API documentation that should likely be changed).

Over slack @arouinfar said it was OK to proceed with one.

**Comment by jessegreenberg** [comment]
Change made above, but I am not sure if there are impacts from deploying phet-io brand to production...Once I hear it is OK from the PhET-iO team Ill go ahead with the deploy command.

**Comment by jessegreenberg** [comment]
I assumed this would be easy but the build tools are giving me trouble:

1) I could not use chipper 2.0 build process because the version of chipper for FAMB was so old, so I had to use https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-1.0.md instead.
2) I tried to patch the `2.3-phetio` branch as well but could not build the phet-io version because `phet-io-wrapper-sonification` repo does not exist. I think that means the `2.3-phetio` branch is no longer being maintained.
3) Attempting to deploy 2.3.19 to production and I got
> Fatal error: Directory [spot.colorado.edu](http://spot.colorado.edu/):/htdocs/physics/phet/dev/html/forces-and-motion-basics/2.3.19 already exists.  If you intend to replace the content then remove the directory manually from [spot.colorado.edu](http://spot.colorado.edu/).

2.3.19 does not exist, but 2.3.19-rc.1 does. I reported the problem on slack, will have to come back to this after I learn more.

**Comment by arouinfar** [comment]
Sounds like a headache @jessegreenberg. Based on this experience, would you recommend avoiding publishing maintenance releases for similarly old sims in the future?

**Comment by jessegreenberg** [comment]
I would not have recommended it if I had known 😆 

But I think this identified a problem with our maintenance tooling and that seems important to get to the bottom of. If this can be fixed, single sim maintenance releases like this should still take little to no time in the future.

**Comment by arouinfar** [comment]
Good to know! Hopefully, the unexpected work will make things smoother in the future.

**Comment by jessegreenberg** [comment]
OK https://github.com/phetsims/chipper/issues/1248 is the resultant issue. But I redeployed this sim and the units change can be seen on the website.

@oliver-phet can you please let the user know?

**Comment by oliver-phet** [comment]
Email to user sent.
