### ISSUE TITLE
Align icons next to checkboxes

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/forces-and-motion-basics#307]
I noticed that the icons are now right-aligned, a nice improvement, but I think they would look best if their alignment was closer to the right edge of the panel. 

Published version: 
![image](https://github.com/phetsims/forces-and-motion-basics/assets/7852916/e074d5a3-2e87-4f08-ae75-8368f95e135f)

Current version: 
![image](https://github.com/phetsims/forces-and-motion-basics/assets/7852916/9a3f229c-0a78-454f-bf9b-41a0d3694d09)

Ideal: 
![image](https://github.com/phetsims/forces-and-motion-basics/assets/7852916/1689015e-b3e3-4f6d-957c-bf9c3882714b)
![image](https://github.com/phetsims/forces-and-motion-basics/assets/7852916/ffa0d9ad-889e-4679-8975-d6381951f5c4)

**Comment by Luisav1** [comment]
I’ve noticed this was assigned to @AgustinVallejo. Since I'm triaging issues to get FAMB ready for dev testing, I’ll address it.

@AgustinVallejo, if there are any objections or additional context, please do share!

**Comment by Luisav1** [comment]
This was fixed in the commit above. @amanda-phet please and review and close if it looks good to you. This is how the Friction and Motion screen controls look like now:
![image](https://github.com/phetsims/forces-and-motion-basics/assets/52978048/8e222f8f-6662-4640-b3c4-4c231dff0502)
![image](https://github.com/phetsims/forces-and-motion-basics/assets/52978048/76379fe2-22ba-4285-a881-4ca95919ba91)

**Comment by amanda-phet** [comment]
Those look great, thanks!!
