### ISSUE TITLE
Update screen icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/forces-and-motion-basics#314]
Related to https://github.com/phetsims/forces-and-motion-basics/issues/310 and https://github.com/phetsims/forces-and-motion-basics/issues/304 

One icon will need to be localized. The others need updating so they have newer artwork integrated.

**Comment by marlitas** [comment]
The query parameter to hide the forces label is: `?showForceArrowLabels=false`

**Comment by marlitas** [comment]
@amanda-phet said this would be a good task for QA to do while the pipeline is light.

**Comment by Nancy-Salpepi** [comment]
The icons are done except for the Net-Force screen. I tried for a long time to get that shot, but the 548x373 dimensions give too much blue and aren't wide enough. The original icon must have been made with Illustrator because the distance between the wagon and the first knot is a lot shorter. There is also more grass. If you are OK with a lot of sky, let me know and I will take it. 

Here is a link to the [folder](https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/Ev26h0PRxPxFs9a1RbQM9qMBDOJrjVwv5K9iNwGk14cwYw), so that you can check them over @amanda-phet. Let me know if any need to be redone. 
If all is good, please commit for me since I do not have those permissions.

**Comment by amanda-phet** [comment]
Thank you @Nancy-Salpepi ! I made a Net Force icon in illustrator and will upload it with other assets so it's there for the future.

**Comment by amanda-phet** [comment]
Icons are all uploaded. @samreid can you let me know when they are ready for review?

**Comment by samreid** [comment]
Added in the commits. Please review by testing on phettest, including but not limited to:
1. Make sure the images are correctly named, and appear as expected.
2. How should the license.json be listed? I wrote https://github.com/phetsims/forces-and-motion-basics/commit/092b5c74d127acbbc3c240421d0f60e9b82be185 based on similar files, but let me know if that needs any changes.

**Comment by amanda-phet** [comment]
I'm not seeing the Motion screen icon change when I select a different region. I tried an incognito window in case there was a caching issue and still didn't see that screen icon update. 

As for the license, these are screenshots of the sim, so I'm not sure how to credit someone since they aren't original art. Nancy took the screenshots for screens 2-4, and I created the Net Force icon in illustrator using assets from the sim. So I would either credit Nancy and myself, or credit the original person listed (perhaps an original designer of the sim? I don't see it in the commit you linked to).

**Comment by samreid** [comment]
I confirmed what @amanda-phet is seeing (missing icons), and found that this well-meaning bot reverted my hard work at 4:36am: https://github.com/phetsims/forces-and-motion-basics/commit/0edbe1b85fa868594886511eebe9c1e206725cad.  I'll revert that commit and open a new issue to discuss this with @zepumph.

I added notes about the net force icon in https://github.com/phetsims/forces-and-motion-basics/commit/09a6ca2e0c70a150e0b2f1f0cd45ac51609603dc. 

Images in https://github.com/phetsims/forces-and-motion-basics/blob/092b5c74d127acbbc3c240421d0f60e9b82be185/images/africa/license.json are credited to Mariah, so it makes sense that screenshots of those images would also be credited to Mariah, so I will leave that as it is unless I hear otherwise.

**Comment by samreid** [comment]
Fixed and ready for review, sorry for the trouble. I confirmed the new images are showing on phettest and not disrupted by `grunt update`.

**Comment by amanda-phet** [comment]
This license file already has some credits, which answers my questions about how to credit a screenshot: https://github.com/phetsims/forces-and-motion-basics/blob/092b5c74d127acbbc3c240421d0f60e9b82be185/images/license.json 

If you want to credit Mariah for those region-specific files that seems fine, but you could also copy what was done here. I'm fine either way! 

The region selection is now showing an updated screen icon, so over to you to close if all is good.
