### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#317]
This simulation is currently JavaScript (5800 LOC) and should be ported to TypeScript.

**Comment by samreid** [comment]
- [ ] eslint-disable
- [ ] ts-nocheck
- [ ] intentionalany
- [ ] export default
- [ ] ts-expect-error

**Comment by marlitas** [comment]
TS countdown:
- ts-expect-error: 21
- eslint-disable: 14
- intentionalAny: 13

**Comment by marlitas** [comment]
There are 5 remaining `eslint-disable` 3 are in simula rasa generated files (aka they will always be there) and the remaining two are `no-view-imported-from-model` which in my opinion is not worth addressing.

There are 2 ts-expect-errors left. These are both in regards to Image typing. It's a bit of a mess in terms of typing due to inheritance, but overall it looks pretty safe. I don't think it's necessary to address before publication.

**Comment by marlitas** [comment]
All remaining `ts-expect-error` and `IntentionalAny` have been addressed. I believe this issue can be closed.
