### ISSUE TITLE
Should the stopwatch be draggable?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#338]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1184
In most sims the stopwatch is draggable. It is not here. Should it be?

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Forces and Motion: Basics‬
URL: https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.4.0-rc.2/phet/forces-and-motion-basics_all_phet.html
Version: 2.4.0-rc.2 2024-12-05 00:58:08 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Ashton-Morris** [comment]
+1 I am used to the stop watching being draggable too.

**Comment by amanda-phet** [comment]
I have never designed or used a sim with a stopwatch before, and reviewed the original issue (https://github.com/phetsims/forces-and-motion-basics/issues/288) and didn't see a specification that it remain fixed or be movable. So if we want it movable, then let's go ahead and do that! But I also don't think it matters a ton in this sim because the play area elements won't really overlap in that part of the sim.

**Comment by marlitas** [comment]
Dragging added above. This issue is ready for cherry-pick

**Comment by Nancy-Salpepi** [comment]
In rc.3 the stopwatch is now draggable across the top portion of the play area. Closing.
